# CLI: CSV-based, human-editable community labeling.
#
# Replaces the earlier ad hoc process (a fresh Claude session, run three
# separate times by hand, reading community word lists against an
# improvised, unsaved prompt) with a documented pipeline stage a historian
# can run - and correct - themselves. See the vault's
# wiki/labeling-pipeline.md for the design this implements, and
# wiki/reproducibility-notes.md for why this buys Tier 1/2 reproducibility
# (same input -> comparable output), not Tier 3 (an LLM call is not
# guaranteed to reproduce the same label text token-for-token even given
# an unchanged input).
#
# Label continuity across periods (2026-08-04): a community's displayed name
# used to be generated independently per period from just that period's top-25
# words, with no link to the Hungarian alignment that already decides
# "moved"/"stayed" for migration_fraction (metrics.align_communities). That
# produced real, reported contradictions - e.g. the word "system" is flagged
# "stayed" between 1760-1780 and 1780-1800 (its community's best-matching
# predecessor really is that same community, confirmed via align_communities),
# but the label text changed anyway ("Books, Manuscripts & Learned Vice" ->
# "Classical Authors & Scholarship") purely because the LLM re-read a
# slightly different top-25 word list and described it differently. To a
# non-technical reader this reads as the tool contradicting itself.
#
# Fix: `generate` now walks periods in chronological order per region and,
# for each community, first checks whether align_communities maps it back to
# a specific predecessor community that already has a label. If so, the
# label/lane are inherited verbatim (origin="inherited", free, deterministic,
# no LLM call) instead of independently regenerated. A community only gets a
# fresh LLM (or manual) label when it is a genuine "genesis" - the region's
# first labeled period, or a community align_communities could not map back
# to any predecessor (i.e. it's the moved-into side of a real reorganization).
# This makes "the label changed" and "the word moved" the same event by
# construction, using the one alignment method already trusted for
# migration_fraction, rather than two independent judgments that can
# disagree.
#
# Three subcommands, meant to be run in this order:
#
#   generate  community_words_res<res>[_<region>].json -> CSV. For each
#             community: inherit from its aligned predecessor when one with
#             an existing label exists (free, always applied - inheritance is
#             deterministic so it's safe to recompute on every run); otherwise
#             it's a genesis community, filled via --fill llm (one API call)
#             or left blank for a human/agent to fill by hand (--fill blank,
#             the default - matches this project's actual practice of using
#             a Claude Code agent instead of a personal API key). Never
#             touches an existing row whose origin is "human". --overwrite
#             also re-fills existing genesis ("llm"/blank) rows, not just gaps.
#   compile   CSV (with any human edits) -> community_labels_res<res>[_<region>].json,
#             the exact file webapp/app.py:get_labels() already reads. No
#             webapp code change needed for this step.
#   publish   copies the current CSV + compiled JSON for a region into the
#             code repo's labels/ directory - a small (~60KB total) citable
#             snapshot, since the label files otherwise live only in the
#             gitignored data repo (see wiki/labeling-pipeline.md, "Why
#             Jamie did not see community names", cause 1).
#
# Usage:
#   python src/label_communities.py generate --region combined
#   python src/label_communities.py generate --region all
#   python src/label_communities.py compile --region combined
#   python src/label_communities.py publish --region combined

import argparse
import csv
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from metrics import MIN_SHARED_WORDS, align_communities
from pipeline_config import REPO_ROOT, discover_built_regions, load_config, variant_label

RESOLUTION = load_config()["leiden"]["label_resolution"]
PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "community_labeling_v1.md"
PROMPT_VERSION = "v1"
DEFAULT_MODEL = "claude-haiku-4-5-20251001"
CSV_FIELDS = ["region", "period", "community_id", "n_words", "top_words_preview",
              "label", "lane", "origin", "inherited_from"]
NON_DETERMINISM_CAVEAT = (
    "Generated by a single LLM read-through of each community's top words, "
    "not an empirically validated taxonomy - a reading aid, not a checked "
    "ground truth. Rerunning `generate` on an unchanged input is not "
    "guaranteed to reproduce the same label text or lane for every "
    "community, since LLM sampling is not bitwise-deterministic even "
    "against an unchanged prompt."
)


def sha256_of(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def parse_prompt_template():
    """Splits community_labeling_v1.md into (lanes, system_prompt,
    user_template) - the lane list is parsed out of the file's own numbered
    list rather than duplicated as a second hardcoded constant, so the
    prompt file stays the one place that list is edited."""
    text = PROMPT_PATH.read_text(encoding="utf-8")

    def section(heading):
        pattern = rf"## {re.escape(heading)}\n(.*?)(?=\n## |\Z)"
        m = re.search(pattern, text, re.DOTALL)
        if not m:
            raise ValueError(f"prompt template missing '## {heading}' section")
        return m.group(1).strip("\n")

    lane_block = section("Fixed lane list")
    lanes = [m.group(1).strip() for m in re.finditer(r"^\d+\.\s+(.+)$", lane_block, re.MULTILINE)]
    if not lanes:
        raise ValueError("no lanes parsed from prompt template's 'Fixed lane list' section")

    system_prompt = section("System prompt")
    user_template = section("User message template")
    return lanes, system_prompt, user_template


def region_label(region):
    return "combined" if region is None else region


def communities_dir_for(config):
    return Path(config["data_root"]) / config["paths"]["communities"]


def words_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_words_res{RESOLUTION}{suffix}.json"


def csv_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_labels_res{RESOLUTION}{suffix}.csv"


def json_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_labels_res{RESOLUTION}{suffix}.json"


def meta_sidecar_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_labels_res{RESOLUTION}{suffix}.generate_meta.json"


def resolve_regions(config, requested):
    if requested == "combined":
        return [None]
    if requested == "all":
        return [None] + list(discover_built_regions(config))
    return [requested]


def load_existing_csv(path):
    """{(period, community_id): row_dict}, empty if the CSV doesn't exist yet."""
    if not path.exists():
        return {}
    with open(path, encoding="utf-8", newline="") as f:
        return {(row["period"], row["community_id"]): row for row in csv.DictReader(f)}


def load_community_csv(path, resolution=RESOLUTION):
    """word -> raw Leiden community id (int) at the given resolution, from a
    <communities>/<variant>.csv file (community.py's output). Used to
    recompute the same alignment metrics.py uses for migration_fraction, so
    label inheritance and moved/stayed always agree."""
    col = f"res_{resolution}"
    out = {}
    with open(path, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            out[row["word"]] = int(row[col])
    return out


def predecessor_mapping(config, variant_prev, variant_curr):
    """{community_id_curr (str): community_id_prev (str)} - which of
    variant_prev's raw communities each of variant_curr's raw communities
    best corresponds to, via the same Hungarian alignment (on shared
    vocabulary) that metrics.align_communities uses for migration_fraction
    and the webapp's moved/stayed flag. Empty if either community CSV is
    missing or the two periods share too few words to align meaningfully
    (mirrors metrics.py's own MIN_SHARED_WORDS floor)."""
    communities_dir = communities_dir_for(config)
    path_prev = communities_dir / f"{variant_prev}.csv"
    path_curr = communities_dir / f"{variant_curr}.csv"
    if not path_prev.exists() or not path_curr.exists():
        return {}

    comm_prev = load_community_csv(path_prev)
    comm_curr = load_community_csv(path_curr)
    shared = sorted(set(comm_prev) & set(comm_curr))
    if len(shared) < MIN_SHARED_WORDS:
        return {}

    labels_prev = [comm_prev[w] for w in shared]
    labels_curr = [comm_curr[w] for w in shared]
    mapping, _ = align_communities(labels_prev, labels_curr)
    return {str(cid_curr): str(cid_prev) for cid_curr, cid_prev in mapping.items()}


def write_csv(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in CSV_FIELDS})


def call_llm(client, model, lanes, system_prompt, user_message, max_attempts=3):
    tool = {
        "name": "assign_label",
        "description": "Assign a plain-English label and lane to this community.",
        "input_schema": {
            "type": "object",
            "properties": {
                "label": {"type": "string", "description": "Two to five word plain-English label."},
                "lane": {"type": "string", "enum": lanes},
            },
            "required": ["label", "lane"],
        },
    }
    last_error = None
    for attempt in range(1, max_attempts + 1):
        try:
            response = client.messages.create(
                model=model,
                max_tokens=300,
                system=system_prompt,
                tools=[tool],
                tool_choice={"type": "tool", "name": "assign_label"},
                messages=[{"role": "user", "content": user_message}],
            )
            for block in response.content:
                if block.type == "tool_use" and block.name == "assign_label":
                    label = str(block.input["label"]).strip()
                    lane = str(block.input["lane"]).strip()
                    if lane not in lanes:
                        raise ValueError(f"model returned lane {lane!r} outside the fixed list")
                    return label, lane
            raise ValueError("no assign_label tool_use block in response")
        except Exception as exc:  # noqa: BLE001 - retry any transient API/parsing failure
            last_error = exc
            if attempt < max_attempts:
                continue
    raise RuntimeError(f"assign_label failed after {max_attempts} attempts: {last_error}")


def cmd_generate(args):
    config = load_config()
    lanes, system_prompt, user_template = parse_prompt_template()

    client = None  # constructed lazily - only needed if --fill llm hits a genesis community

    def get_client():
        nonlocal client
        if client is None:
            try:
                import anthropic
            except ImportError:
                sys.exit("anthropic package not installed - run: pip install -r requirements.txt")
            client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from the environment
        return client

    base_labels = [lbl for _, _, lbl in config["periods"]]

    for region in resolve_regions(config, args.region):
        words_path = words_path_for(config, region)
        if not words_path.exists():
            print(f"skip {region_label(region)}: {words_path} not found - run src/extract_community_words.py first")
            continue

        with open(words_path, encoding="utf-8") as f:
            words_data = json.load(f)

        csv_path = csv_path_for(config, region)
        existing = load_existing_csv(csv_path)

        rows = []
        n_inherited = 0
        n_pending = 0
        n_called = 0
        n_blank = 0
        n_kept = 0

        prev_period = None
        prev_labels = {}  # {raw_cid (str): {"label":..., "lane":...}} for prev_period

        for period in base_labels:
            if period not in words_data:
                continue
            communities = words_data[period]

            mapping = {}
            if prev_period is not None:
                mapping = predecessor_mapping(
                    config, variant_label(prev_period, region), variant_label(period, region)
                )

            period_labels = {}
            for cid, info in communities.items():
                key = (period, cid)
                prior = existing.get(key)
                base_row = {
                    "region": region_label(region),
                    "period": period,
                    "community_id": cid,
                    "n_words": info["n_words"],
                    "top_words_preview": "; ".join(info["top_words"][:10]),
                }

                if prior is not None and prior.get("origin") == "human":
                    row = {**base_row, "label": prior["label"], "lane": prior["lane"],
                           "origin": "human", "inherited_from": prior.get("inherited_from", "")}
                    rows.append(row)
                    period_labels[cid] = {"label": row["label"], "lane": row["lane"]}
                    n_kept += 1
                    continue

                predecessor = mapping.get(cid)
                if predecessor is not None:
                    predecessor_entry = prev_labels.get(predecessor)
                    if predecessor_entry is not None:
                        row = {**base_row, "label": predecessor_entry["label"], "lane": predecessor_entry["lane"],
                               "origin": "inherited", "inherited_from": f"{prev_period}#{predecessor}"}
                        rows.append(row)
                        period_labels[cid] = {"label": row["label"], "lane": row["lane"]}
                        n_inherited += 1
                        continue

                    # Structurally a continuation (align_communities does map it
                    # to a specific predecessor), but that predecessor has no
                    # resolved text anywhere yet - typically because it's itself
                    # still an unfilled genesis row on a cold region's first
                    # pass. Left blank with origin="inherited" (NOT routed to
                    # the genesis fill below) so a plain rerun - no agent, no
                    # LLM call - resolves it for free once the true genesis row
                    # upstream gets real text, and so an agent filling genesis
                    # rows never wastes effort independently re-reading a
                    # community that was always going to inherit anyway.
                    row = {**base_row, "label": "", "lane": "", "origin": "inherited",
                           "inherited_from": f"{prev_period}#{predecessor}"}
                    rows.append(row)
                    n_pending += 1
                    continue

                # genesis community: align_communities found no predecessor at all -
                # this is a genuine first appearance (region's first labeled period,
                # or the moved-into side of a real reorganization). Existing
                # text (even "llm"-origin from a previous run) is kept as-is unless
                # a fresh LLM call was explicitly requested for it - blank is only
                # for a community that has never had any label text at all, so a
                # --fill blank run never regresses already-labeled genesis rows
                # into blanks, and downstream periods still have real text to
                # inherit from.
                if prior is not None and prior.get("label") and not (args.overwrite and args.fill == "llm"):
                    row = {**base_row, "label": prior["label"], "lane": prior["lane"],
                           "origin": prior.get("origin") or "llm", "inherited_from": ""}
                    rows.append(row)
                    period_labels[cid] = {"label": row["label"], "lane": row["lane"]}
                    n_kept += 1
                    continue

                if args.fill == "llm":
                    user_message = user_template.format(
                        region=region_label(region),
                        period=period,
                        n_words=info["n_words"],
                        n_shown=len(info["top_words"]),
                        top_words=", ".join(info["top_words"]),
                    )
                    label, lane = call_llm(get_client(), args.model, lanes, system_prompt, user_message)
                    row = {**base_row, "label": label, "lane": lane, "origin": "llm", "inherited_from": ""}
                    period_labels[cid] = {"label": label, "lane": lane}
                    n_called += 1
                    print(f"{region_label(region)} {period} #{cid} (genesis): {label} [{lane}]")
                else:
                    row = {**base_row, "label": "", "lane": "", "origin": "", "inherited_from": ""}
                    n_blank += 1
                rows.append(row)

            prev_period = period
            prev_labels = period_labels

        write_csv(csv_path, rows)

        meta = {
            "model": args.model,
            "prompt_file": PROMPT_PATH.relative_to(REPO_ROOT).as_posix(),
            "prompt_version": PROMPT_VERSION,
            "prompt_sha256_16": sha256_of(PROMPT_PATH),
            "source_words_file": words_path.name,
            "source_words_sha256_16": sha256_of(words_path),
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        with open(meta_sidecar_path_for(config, region), "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)

        print(f"{region_label(region)}: {n_inherited} inherited, {n_pending} pending (structurally "
              f"inherited, waiting on an unresolved predecessor - rerun generate once genesis rows "
              f"below are filled), {n_called} labeled via LLM, {n_blank} genesis rows left blank for "
              f"manual fill, {n_kept} kept from existing CSV -> {csv_path}")
        if n_blank:
            print(f"{region_label(region)}: {n_blank} genesis communities need a label - fill only "
                  f"the rows with an empty 'origin' (not 'inherited') in {csv_path} by hand or via an "
                  f"agent, then rerun generate (resolves the {n_pending} pending rows for free) and compile.")


def cmd_compile(args):
    config = load_config()

    for region in resolve_regions(config, args.region):
        csv_path = Path(args.csv) if args.csv else csv_path_for(config, region)
        if not csv_path.exists():
            print(f"skip {region_label(region)}: {csv_path} not found - run generate first")
            continue

        with open(csv_path, encoding="utf-8", newline="") as f:
            rows = list(csv.DictReader(f))

        out = {}
        n_human = 0
        n_inherited = 0
        n_blank = 0
        for row in rows:
            label = row["label"].strip()
            lane = row["lane"].strip()
            if not label:
                n_blank += 1
                continue  # unfilled genesis row - leave out of the compiled JSON rather than publish an empty label
            # No "(mixed)" suffix baked into the label text: the `lane` field
            # already carries "this isn't a real topic" (lane ==
            # "Structural / Uncertain"), and appending the word "mixed" to an
            # already-decisive description ("Second-Person Verb Forms",
            # "Biblical Book Abbreviations") made even a clear grammatical
            # reading look like the tool couldn't figure it out. The webapp's
            # own stripMixedTag() already treats a literal "(mixed)" in older
            # label text as redundant with the lane - this just stops writing
            # the redundant text in the first place.
            entry = {
                "label": label,
                "n_words": int(row["n_words"]),
                "lane": lane,
            }
            if row.get("inherited_from"):
                entry["inherited_from"] = row["inherited_from"]
            out.setdefault(row["period"], {})[row["community_id"]] = entry
            if row.get("origin") == "human":
                n_human += 1
            elif row.get("origin") == "inherited":
                n_inherited += 1

        if n_blank:
            print(f"{region_label(region)}: {n_blank} rows have no label yet - "
                  f"skipped in the compiled JSON (fill them in the CSV and recompile)")

        meta_path = meta_sidecar_path_for(config, region)
        meta_extra = {}
        if meta_path.exists():
            with open(meta_path, encoding="utf-8") as f:
                meta_extra = json.load(f)

        out["_meta"] = {
            "resolution": RESOLUTION,
            "region": region_label(region),
            "n_communities": len(rows),
            "n_human_edited": n_human,
            "n_inherited": n_inherited,
            "method": NON_DETERMINISM_CAVEAT,
            "compiled_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            **meta_extra,
        }

        json_path = json_path_for(config, region)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False)
        print(f"{region_label(region)}: {len(rows)} communities ({n_human} human-edited) -> {json_path}")


def cmd_publish(args):
    config = load_config()
    dest_dir = REPO_ROOT / "labels"
    dest_dir.mkdir(parents=True, exist_ok=True)

    import shutil

    for region in resolve_regions(config, args.region):
        for src in (csv_path_for(config, region), json_path_for(config, region)):
            if not src.exists():
                print(f"skip {src.name}: not found")
                continue
            dest = dest_dir / src.name
            shutil.copy2(src, dest)
            print(f"published -> {dest.relative_to(REPO_ROOT)}")

    print("Files are copied to disk only - review and `git add labels/` yourself, this script never commits.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p_gen = sub.add_parser("generate", help="community_words JSON -> CSV, inheriting labels across periods where possible")
    p_gen.add_argument("--region", default="combined", help="'combined', a region name, or 'all'")
    p_gen.add_argument("--model", default=DEFAULT_MODEL)
    p_gen.add_argument("--fill", choices=["blank", "llm"], default="blank",
                        help="How to fill genesis communities (no inheritable predecessor): "
                             "'blank' (default) leaves label/lane empty for a human or Claude Code "
                             "agent to fill in the CSV directly; 'llm' calls the API "
                             "(needs ANTHROPIC_API_KEY) instead")
    p_gen.add_argument("--overwrite", action="store_true",
                        help="Re-fill existing genesis rows too, not just gaps (human rows are never "
                             "touched; inherited rows are always recomputed regardless of this flag)")
    p_gen.set_defaults(func=cmd_generate)

    p_compile = sub.add_parser("compile", help="CSV (with any human edits) -> community_labels JSON")
    p_compile.add_argument("--region", default="combined", help="'combined', a region name, or 'all'")
    p_compile.add_argument("--csv", default=None, help="Override the input CSV path (single-region only)")
    p_compile.set_defaults(func=cmd_compile)

    p_pub = sub.add_parser("publish", help="Copy CSV + compiled JSON into the code repo's labels/ directory")
    p_pub.add_argument("--region", default="combined", help="'combined', a region name, or 'all'")
    p_pub.set_defaults(func=cmd_publish)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
