# CLI: CSV-based, human-editable community labeling.
#
# Replaces the earlier ad hoc process (a fresh Claude session, run three
# separate times by hand, reading community word lists against an
# improvised, unsaved prompt) with a documented pipeline stage a historian
# can run - and correct - themselves. See the vault's
# wiki/labeling-pipeline.md for the design this implements, and
# wiki/reproducibility-notes.md for why this buys Tier 1/2 reproducibility
# (same input -> comparable output), not Tier 3 (an LLM call is not
# guaranteed to reproduce the same label text token-for-token even given
# an unchanged input).
#
# Three subcommands, meant to be run in this order:
#
#   generate  community_words_res<res>[_<region>].json -> CSV (LLM pre-fill,
#             one call per community). Never overwrites an existing row
#             whose origin is "human"; by default also leaves existing
#             "llm" rows alone so a rerun only fills in gaps - pass
#             --overwrite to relabel existing llm rows too.
#   compile   CSV (with any human edits) -> community_labels_res<res>[_<region>].json,
#             the exact file webapp/app.py:get_labels() already reads. No
#             webapp code change needed for this step.
#   publish   copies the current CSV + compiled JSON for a region into the
#             code repo's labels/ directory - a small (~60KB total) citable
#             snapshot, since the label files otherwise live only in the
#             gitignored data repo (see wiki/labeling-pipeline.md, "Why
#             Jamie did not see community names", cause 1).
#
# Usage:
#   python src/label_communities.py generate --region combined
#   python src/label_communities.py generate --region all
#   python src/label_communities.py compile --region combined
#   python src/label_communities.py publish --region combined

import argparse
import csv
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pipeline_config import REPO_ROOT, discover_built_regions, load_config, variant_label

RESOLUTION = 1.0
PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "community_labeling_v1.md"
PROMPT_VERSION = "v1"
DEFAULT_MODEL = "claude-haiku-4-5-20251001"
CSV_FIELDS = ["region", "period", "community_id", "n_words", "top_words_preview", "label", "lane", "origin"]
NON_DETERMINISM_CAVEAT = (
    "Generated by a single LLM read-through of each community's top words, "
    "not an empirically validated taxonomy - a reading aid, not a checked "
    "ground truth. Rerunning `generate` on an unchanged input is not "
    "guaranteed to reproduce the same label text or lane for every "
    "community, since LLM sampling is not bitwise-deterministic even "
    "against an unchanged prompt."
)


def sha256_of(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def parse_prompt_template():
    """Splits community_labeling_v1.md into (lanes, system_prompt,
    user_template) - the lane list is parsed out of the file's own numbered
    list rather than duplicated as a second hardcoded constant, so the
    prompt file stays the one place that list is edited."""
    text = PROMPT_PATH.read_text(encoding="utf-8")

    def section(heading):
        pattern = rf"## {re.escape(heading)}\n(.*?)(?=\n## |\Z)"
        m = re.search(pattern, text, re.DOTALL)
        if not m:
            raise ValueError(f"prompt template missing '## {heading}' section")
        return m.group(1).strip("\n")

    lane_block = section("Fixed lane list")
    lanes = [m.group(1).strip() for m in re.finditer(r"^\d+\.\s+(.+)$", lane_block, re.MULTILINE)]
    if not lanes:
        raise ValueError("no lanes parsed from prompt template's 'Fixed lane list' section")

    system_prompt = section("System prompt")
    user_template = section("User message template")
    return lanes, system_prompt, user_template


def region_label(region):
    return "combined" if region is None else region


def communities_dir_for(config):
    return Path(config["data_root"]) / config["paths"]["communities"]


def words_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_words_res{RESOLUTION}{suffix}.json"


def csv_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_labels_res{RESOLUTION}{suffix}.csv"


def json_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_labels_res{RESOLUTION}{suffix}.json"


def meta_sidecar_path_for(config, region):
    suffix = "" if region is None else f"_{region}"
    return communities_dir_for(config) / f"community_labels_res{RESOLUTION}{suffix}.generate_meta.json"


def resolve_regions(config, requested):
    if requested == "combined":
        return [None]
    if requested == "all":
        return [None] + list(discover_built_regions(config))
    return [requested]


def load_existing_csv(path):
    """{(period, community_id): row_dict}, empty if the CSV doesn't exist yet."""
    if not path.exists():
        return {}
    with open(path, encoding="utf-8", newline="") as f:
        return {(row["period"], row["community_id"]): row for row in csv.DictReader(f)}


def write_csv(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in CSV_FIELDS})


def call_llm(client, model, lanes, system_prompt, user_message, max_attempts=3):
    tool = {
        "name": "assign_label",
        "description": "Assign a plain-English label and lane to this community.",
        "input_schema": {
            "type": "object",
            "properties": {
                "label": {"type": "string", "description": "Two to five word plain-English label."},
                "lane": {"type": "string", "enum": lanes},
            },
            "required": ["label", "lane"],
        },
    }
    last_error = None
    for attempt in range(1, max_attempts + 1):
        try:
            response = client.messages.create(
                model=model,
                max_tokens=300,
                system=system_prompt,
                tools=[tool],
                tool_choice={"type": "tool", "name": "assign_label"},
                messages=[{"role": "user", "content": user_message}],
            )
            for block in response.content:
                if block.type == "tool_use" and block.name == "assign_label":
                    label = str(block.input["label"]).strip()
                    lane = str(block.input["lane"]).strip()
                    if lane not in lanes:
                        raise ValueError(f"model returned lane {lane!r} outside the fixed list")
                    return label, lane
            raise ValueError("no assign_label tool_use block in response")
        except Exception as exc:  # noqa: BLE001 - retry any transient API/parsing failure
            last_error = exc
            if attempt < max_attempts:
                continue
    raise RuntimeError(f"assign_label failed after {max_attempts} attempts: {last_error}")


def cmd_generate(args):
    config = load_config()
    lanes, system_prompt, user_template = parse_prompt_template()

    try:
        import anthropic
    except ImportError:
        sys.exit("anthropic package not installed - run: pip install -r requirements.txt")

    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from the environment

    for region in resolve_regions(config, args.region):
        words_path = words_path_for(config, region)
        if not words_path.exists():
            print(f"skip {region_label(region)}: {words_path} not found - run src/extract_community_words.py first")
            continue

        with open(words_path, encoding="utf-8") as f:
            words_data = json.load(f)

        csv_path = csv_path_for(config, region)
        existing = load_existing_csv(csv_path)

        rows = []
        n_called = 0
        n_kept = 0
        for period, communities in words_data.items():
            for cid, info in communities.items():
                key = (period, cid)
                prior = existing.get(key)
                skip_call = prior is not None and (
                    prior.get("origin") == "human" or (prior.get("origin") == "llm" and not args.overwrite)
                )
                if skip_call:
                    rows.append({
                        "region": region_label(region),
                        "period": period,
                        "community_id": cid,
                        "n_words": info["n_words"],
                        "top_words_preview": "; ".join(info["top_words"][:10]),
                        "label": prior["label"],
                        "lane": prior["lane"],
                        "origin": prior["origin"],
                    })
                    n_kept += 1
                    continue

                user_message = user_template.format(
                    region=region_label(region),
                    period=period,
                    n_words=info["n_words"],
                    n_shown=len(info["top_words"]),
                    top_words=", ".join(info["top_words"]),
                )
                label, lane = call_llm(client, args.model, lanes, system_prompt, user_message)
                rows.append({
                    "region": region_label(region),
                    "period": period,
                    "community_id": cid,
                    "n_words": info["n_words"],
                    "top_words_preview": "; ".join(info["top_words"][:10]),
                    "label": label,
                    "lane": lane,
                    "origin": "llm",
                })
                n_called += 1
                print(f"{region_label(region)} {period} #{cid}: {label} [{lane}]")

        write_csv(csv_path, rows)

        meta = {
            "model": args.model,
            "prompt_file": PROMPT_PATH.relative_to(REPO_ROOT).as_posix(),
            "prompt_version": PROMPT_VERSION,
            "prompt_sha256_16": sha256_of(PROMPT_PATH),
            "source_words_file": words_path.name,
            "source_words_sha256_16": sha256_of(words_path),
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        }
        with open(meta_sidecar_path_for(config, region), "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)

        print(f"{region_label(region)}: {n_called} labeled, {n_kept} kept from existing CSV -> {csv_path}")


def cmd_compile(args):
    config = load_config()

    for region in resolve_regions(config, args.region):
        csv_path = Path(args.csv) if args.csv else csv_path_for(config, region)
        if not csv_path.exists():
            print(f"skip {region_label(region)}: {csv_path} not found - run generate first")
            continue

        with open(csv_path, encoding="utf-8", newline="") as f:
            rows = list(csv.DictReader(f))

        out = {}
        n_human = 0
        for row in rows:
            label = row["label"].strip()
            lane = row["lane"].strip()
            if lane == "Structural / Uncertain" and "(mixed)" not in label.lower():
                label = f"{label} (mixed)"
            out.setdefault(row["period"], {})[row["community_id"]] = {
                "label": label,
                "n_words": int(row["n_words"]),
                "lane": lane,
            }
            if row.get("origin") == "human":
                n_human += 1

        meta_path = meta_sidecar_path_for(config, region)
        meta_extra = {}
        if meta_path.exists():
            with open(meta_path, encoding="utf-8") as f:
                meta_extra = json.load(f)

        out["_meta"] = {
            "resolution": RESOLUTION,
            "region": region_label(region),
            "n_communities": len(rows),
            "n_human_edited": n_human,
            "method": NON_DETERMINISM_CAVEAT,
            "compiled_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            **meta_extra,
        }

        json_path = json_path_for(config, region)
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False)
        print(f"{region_label(region)}: {len(rows)} communities ({n_human} human-edited) -> {json_path}")


def cmd_publish(args):
    config = load_config()
    dest_dir = REPO_ROOT / "labels"
    dest_dir.mkdir(parents=True, exist_ok=True)

    import shutil

    for region in resolve_regions(config, args.region):
        for src in (csv_path_for(config, region), json_path_for(config, region)):
            if not src.exists():
                print(f"skip {src.name}: not found")
                continue
            dest = dest_dir / src.name
            shutil.copy2(src, dest)
            print(f"published -> {dest.relative_to(REPO_ROOT)}")

    print("Files are copied to disk only - review and `git add labels/` yourself, this script never commits.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p_gen = sub.add_parser("generate", help="LLM pre-fill: community_words JSON -> CSV")
    p_gen.add_argument("--region", default="combined", help="'combined', a region name, or 'all'")
    p_gen.add_argument("--model", default=DEFAULT_MODEL)
    p_gen.add_argument("--overwrite", action="store_true", help="Relabel existing llm-origin rows too (human rows are never touched)")
    p_gen.set_defaults(func=cmd_generate)

    p_compile = sub.add_parser("compile", help="CSV (with any human edits) -> community_labels JSON")
    p_compile.add_argument("--region", default="combined", help="'combined', a region name, or 'all'")
    p_compile.add_argument("--csv", default=None, help="Override the input CSV path (single-region only)")
    p_compile.set_defaults(func=cmd_compile)

    p_pub = sub.add_parser("publish", help="Copy CSV + compiled JSON into the code repo's labels/ directory")
    p_pub.add_argument("--region", default="combined", help="'combined', a region name, or 'all'")
    p_pub.set_defaults(func=cmd_publish)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
